### ISSUE TITLE
Windows python 2.7.13 pex 1.2.13 requires wheel==0.29.0

### ISSUE THREAD

**Issue by adobeDan** [adobe-apiplatform/user-sync.py#290]
The latest wheel version on Windows (0.30.0), when run with Python 2.7.13 and pex 1.2.13, produces a build error:
```sh
  File "c:\cygwin64\home\dbrotsky\build27\lib\site-packages\pex\bin\pex.py", line 423, in _safe_link
    os.symlink(src, dst)
AttributeError: 'module' object has no attribute 'symlink'
```
The workaround is to build with wheel 0.29.0.

**Comment by adobeDan** [comment]
Turns out that pex requires wheel to be less than version 30.  From the PEX source ` version.py`:
```py
WHEEL_REQUIREMENT = 'wheel>=0.26.0,<0.30.0'
```
So we need our makefile to have the same restriction.
