### ISSUE TITLE
Unhandled exception using adobe-only-user-list

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#457]
**User Sync version**: 2.4
**Python version:** 3.6.6 on win32
 **Command line arguments:** -t --adobe-only-user-list remove-this.csv --adobe-only-user-action remove

**Error:**
 Unhandled exception
Traceback (most recent call last):
  File "c:\pex\install\user_sync-2.4-py3-none-any.whl.e73f62b1b429ec85c7c69c1c3aed30acfe296aca\user_sync-2.4-py3-none-any.whl\user_sync\app.py", line 85, in main
    begin_work(config_loader)
  File "c:\pex\install\user_sync-2.4-py3-none-any.whl.e73f62b1b429ec85c7c69c1c3aed30acfe296aca\user_sync-2.4-py3-none-any.whl\user_sync\app.py", line 315, in begin_work
    directory_connector.state.additional_group_filters = additional_group_filters
AttributeError: 'NoneType' object has no attribute 'state'

Same thing works on v2.3
